# Generated by Django 1.11.2 on 2018-01-30 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("birds", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataCollection",
        ),
        migrations.DeleteModel(
            name="DataType",
        ),
    ]
