# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:15
from __future__ import unicode_literals

import uuid
from django.db import migrations, models
import django.db.models.deletion


def clear_animals(apps, schema_editor):
    Animal = apps.get_model("birds", "Animal")
    for animal in Animal.objects.all():
        animal.delete()

def clear_events(apps, schema_editor):
    Event = apps.get_model("birds", "Event")
    for event in Event.objects.all():
        event.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_auto_20161109_1215'),
    ]

    operations = [
        # remove all animals; will need to repopulate
        migrations.RunPython(clear_animals, migrations.RunPython.noop),
        migrations.RunPython(clear_events, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
