# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20180322_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='count',
        ),
        migrations.AlterField(
            model_name='status',
            name='category',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='category of animal in protocol', max_length=2, null=True),
        ),
    ]
