# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20161109_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
