# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20161102_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
