# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_auto_20161107_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='abbrv',
            field=models.CharField(max_length=3, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
