# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_auto_20161108_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='birds.Animal')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='birds.Animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='parentz',
            field=models.ManyToManyField(related_name='children', through='birds.Parent', to='birds.Animal'),
        ),
    ]
