# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_auto_20161108_1623'),
    ]

    operations = [
        migrations.RunSQL(
            ["INSERT INTO birds_parent (id, child_id, parent_id) SELECT id, from_animal_id, to_animal_id FROM birds_animal_parents;"],
            migrations.RunSQL.noop
        )
    ]
