# Generated by Django 2.2.9 on 2019-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_auto_20190703_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='max_days',
        ),
    ]
