# Generated by Django 2.2.9 on 2020-01-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0010_location_nest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': ['date', 'created'], 'ordering': ['-date', '-created']},
        ),
        migrations.AddField(
            model_name='species',
            name='incubation_days',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
