# Generated by Django 4.1.5 on 2024-01-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0014_auto_20220401_1217'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['animal', 'status'], name='animal_status_idx'),
        ),
    ]
