# Generated by Django 4.1.5 on 2024-04-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0018_alter_pairing_options_remove_pairing_ended_gt_began_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
