# Generated by Django 5.1.4 on 2025-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birds", "0024_add_status_constraint_and_indices"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(fields=["parent"], name="parent_idx"),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(fields=["child"], name="child_idx"),
        ),
    ]
