# Generated by Django 4.2.17 on 2025-06-21 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birds", "0027_alter_status_adds_animallifehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="animallifehistory",
            name="last_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="birds.location",
            ),
        ),
        migrations.AlterField(
            model_name="animallifehistory",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
