# Generated by Django 4.2.17 on 2025-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birds", "0028_animallifehistory_last_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animallifehistory",
            name="has_any_event",
        ),
        migrations.AddField(
            model_name="animallifehistory",
            name="first_event_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
