# Generated by Django 5.1.4 on 2025-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birds", "0029_remove_animallifehistory_has_any_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animallifehistory",
            name="inbreeding_coefficient",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
