# Generated by Django 5.1.4 on 2025-06-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("birds", "0031_room_alter_location_options_location_room"),
        ("birds", "0032_location_active"),
    ]

    dependencies = [
        ("birds", "0030_animallifehistory_inbreeding_coefficient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45, unique=True)),
                ("description", models.TextField(default="")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("room", "name")},
        ),
        migrations.AddField(
            model_name="location",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="birds.room",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="active",
            field=models.BooleanField(
                default=True, help_text="select if the location currently exists"
            ),
        ),
    ]
