# Generated by Django 5.1.4 on 2025-06-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0031_room_alter_location_options_location_room_squashed_0032_location_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('room', 'name')},
        ),
    ]
