# Generated by Django 5.1.4 on 2025-08-12 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("birds", "0033_alter_location_name_alter_location_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "get_latest_by": ("date", "created_at"),
                "ordering": ("-date", "-created_at"),
            },
        ),
        migrations.RenameField(
            model_name="animal",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="measurement",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="pairing",
            old_name="created",
            new_name="created_at",
        ),
    ]
