# Generated by Django 5.1.4 on 2025-08-17 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "birds",
            "0035_tag_animaltag_animal_tags_squashed_0036_alter_tag_options_alter_animal_tags",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="reserved_by",
        ),
    ]
