name: Test app

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.2"]
        numpy-version: ["1.26", "2.1"]
            
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Add a health check to ensure postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        version: "latest"
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        DJANGO_VERSION: ${{ matrix.django-version }}
        NUMPY_VERSION: ${{ matrix.numpy-version }}
      run: |
        uv sync --frozen
        uv add "Django~=${DJANGO_VERSION}"
        uv add "numpy>=$NUMPY_VERSION,<$(echo "$NUMPY_VERSION" | awk -F. '{print $1"."($2+1)}')"
    - name: Run tests on python ${{ matrix.python-version }}
      run: uv run pytest        
